// src/views/AdminBookingListView.tsx
import React, { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useBooking, BookingResponse } from '../context/BookingContext';
import { useAuth } from '../context/AuthContext';
import Swal from 'sweetalert2';

const AdminBookingListView: React.FC = () => {
  const { bookings, cancelBooking, fetchMisReservas } = useBooking();
  const { token } = useAuth();

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedStatusFilter, setSelectedStatusFilter] = useState<'all' | 'confirmed' | 'completed' | 'cancelled'>('all');
  const [expandedBookingId, setExpandedBookingId] = useState('');

  const toggleExpand = (id: string) => {
    setExpandedBookingId(prev => prev === id ? '' : id);
  };

  const getStatusClass = (statusName: string) => {
    switch (statusName) {
      case 'Confirmed':
      case 'Confirmada':
        return 'bg-success-green/10 text-success-green border border-success-green/20';
      case 'Completed':
      case 'Completada':
        return 'bg-secondary/10 text-secondary border border-secondary/20';
      case 'Cancelled':
      case 'Cancelada':
        return 'bg-error/10 text-error border border-error/20';
      default:
        return 'bg-surface-variant text-outline border border-outline-variant';
    }
  };

  const filteredBookings = useMemo(() => {
    return bookings.filter(b => {
      // Filtro por Estado
      if (selectedStatusFilter !== 'all') {
        const statusLower = (b.statusName || '').toLowerCase();
        if (selectedStatusFilter === 'confirmed' && !statusLower.includes('confirm')) return false;
        if (selectedStatusFilter === 'completed' && !statusLower.includes('complet')) return false;
        if (selectedStatusFilter === 'cancelled' && !statusLower.includes('cancel')) return false;
      }

      // Filtro por buscador (PNR, pasajero, atracción)
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchPnr = (b.pnrCode || '').toLowerCase().includes(q);
        const matchAttr = (b.attractionName || '').toLowerCase().includes(q);
        const matchPassenger = b.passengers?.some(p => 
          `${p.firstName || ''} ${p.lastName || ''} ${p.fullName || ''}`.toLowerCase().includes(q)
        ) || false;

        return matchPnr || matchAttr || matchPassenger;
      }

      return true;
    });
  }, [bookings, selectedStatusFilter, searchQuery]);

  const handleCancel = (booking: BookingResponse) => {
    if (!token) {
      Swal.fire({
        title: 'Error',
        text: 'Debes tener una sesión administrativa activa para realizar esta acción.',
        icon: 'error',
        confirmButtonColor: '#ba1a1a'
      });
      return;
    }

    Swal.fire({
      title: '¿Cancelar esta Reserva?',
      text: `Se liberarán los cupos correspondientes. Por favor, escribe el motivo de la cancelación administrativa:`,
      input: 'text',
      inputPlaceholder: 'Ej: Cancelación solicitada por el cliente...',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#ba1a1a',
      cancelButtonColor: '#747782',
      confirmButtonText: 'Sí, cancelar y liberar',
      cancelButtonText: 'Volver',
      inputValidator: (value) => {
        if (!value) {
          return '¡Es obligatorio indicar un motivo!';
        }
      }
    }).then(async (result) => {
      if (result.isConfirmed) {
        const reason = result.value;
        const res = await cancelBooking(booking.id, reason, token);
        if (res.success) {
          Swal.fire({
            title: 'Reserva Cancelada',
            text: 'La reserva ha sido anulada y los cupos de disponibilidad fueron devueltos con éxito.',
            icon: 'success',
            confirmButtonColor: '#0058bc'
          });
          fetchMisReservas(token);
        } else {
          Swal.fire({
            title: 'Error',
            text: res.message || 'No se pudo cancelar la reserva.',
            icon: 'error',
            confirmButtonColor: '#ba1a1a'
          });
        }
      }
    });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex flex-col gap-6 text-left">
      
      {/* Encabezado */}
      <div className="flex flex-col gap-1 border-b border-surface-variant pb-4">
        <Link to="/admin" className="text-xs font-bold text-secondary hover:underline flex items-center gap-1">
          <span className="material-symbols-outlined text-xs">arrow_back</span>
          <span>Volver al Dashboard</span>
        </Link>
        <h1 className="text-2xl md:text-3xl font-extrabold text-primary">Buscador y Control de Reservas</h1>
      </div>

      {/* Buscador y Filtros */}
      <div className="bg-white rounded-2xl p-4 border border-surface-variant flex flex-col md:flex-row gap-4 items-center justify-between shadow-sm">
        {/* Buscador */}
        <div className="flex items-center rounded-xl bg-background border border-outline-variant px-3 py-1.5 w-full md:max-w-sm focus-within:border-secondary">
          <span className="material-symbols-outlined text-outline text-lg">search</span>
          <input 
            type="text" 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Buscar por PNR, pasajero o atracción..." 
            className="w-full bg-transparent border-none text-primary text-xs pl-2 py-1 placeholder-outline focus:outline-none"
          />
        </div>

        {/* Filtros */}
        <div className="flex items-center gap-1.5 flex-wrap">
          {[
            { id: 'all', label: 'Todos' },
            { id: 'confirmed', label: 'Confirmadas' },
            { id: 'completed', label: 'Completadas' },
            { id: 'cancelled', label: 'Canceladas' }
          ].map(f => (
            <button 
              key={f.id}
              onClick={() => setSelectedStatusFilter(f.id as any)}
              className={`px-3.5 py-1.5 rounded-lg text-[10px] font-bold uppercase transition-all cursor-pointer border ${
                selectedStatusFilter === f.id
                  ? 'bg-secondary text-white border-secondary shadow-sm'
                  : 'bg-background border-surface-variant text-outline hover:border-outline'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
      </div>

      {/* Listado */}
      <div className="flex flex-col gap-4">
        {filteredBookings.length === 0 ? (
          <div className="bg-white rounded-2xl p-16 text-center border border-surface-variant text-outline text-xs shadow-sm">
            No se encontraron reservas que coincidan con los filtros de búsqueda.
          </div>
        ) : (
          filteredBookings.map(booking => {
            const isExpanded = expandedBookingId === booking.id;
            
            return (
              <div 
                key={booking.id}
                className={`bg-white rounded-2xl border transition-all duration-200 shadow-sm ${
                  isExpanded ? 'border-secondary' : 'border-surface-variant hover:border-outline'
                }`}
              >
                {/* Cabecera Item */}
                <div 
                  onClick={() => toggleExpand(booking.id)}
                  className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 cursor-pointer text-xs"
                >
                  <div className="flex items-start gap-3">
                    <span className="material-symbols-outlined text-secondary text-2xl">local_activity</span>
                    <div className="flex flex-col text-left gap-0.5">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-extrabold text-sm text-secondary font-mono uppercase tracking-wider">
                          {booking.pnrCode}
                        </span>
                        <span className="font-bold text-primary truncate w-40 md:w-56">{booking.attractionName}</span>
                      </div>
                      <span className="text-[10px] text-outline font-semibold">Reserva Digital HospédateEC</span>
                    </div>
                  </div>

                  <div className="flex items-center justify-between md:justify-end gap-5 border-t border-surface-variant md:border-none pt-3 md:pt-0">
                    <div className="flex flex-col text-right pr-4 border-r border-surface-variant">
                      <span className="text-[8px] text-outline uppercase font-semibold">Actividad programada</span>
                      <span className="font-bold text-primary">
                        {booking.slotDate.split('-').reverse().join('/')} | {booking.slotStartTime} hs
                      </span>
                    </div>

                    <div className="flex items-center gap-3">
                      <span className={`px-2.5 py-1 rounded-full text-[9px] font-bold uppercase tracking-wider ${getStatusClass(booking.statusName)}`}>
                        {booking.statusName}
                      </span>
                      <span className={`material-symbols-outlined text-outline transition-transform duration-200 ${isExpanded ? 'rotate-180' : ''}`}>
                        expand_more
                      </span>
                    </div>
                  </div>
                </div>

                {/* Detalles desplegados */}
                {isExpanded && (
                  <div className="px-5 pb-5 border-t border-surface-variant pt-4 flex flex-col gap-4 text-xs">
                    
                    {/* Pasajeros */}
                    <div>
                      <h4 className="text-[10px] font-bold text-outline uppercase tracking-wider mb-2">Pasajeros Facturados</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                        {booking.passengers?.map((p, pIdx) => (
                          <div 
                            key={pIdx}
                            className="p-3 rounded-xl bg-background border border-surface-variant flex flex-col gap-1 text-left"
                          >
                            <div className="font-bold text-primary">{p.fullName || `${p.firstName} ${p.lastName}`}</div>
                            <div className="flex justify-between text-[10px] text-outline font-semibold">
                              <span>Doc: {p.documentNumber}</span>
                              <span className="text-secondary">{p.priceTierLabel || p.ticketCategoryName} (${(p.unitPrice || 0).toFixed(2)})</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Bitácora de cobro */}
                    <div className="p-3.5 rounded-xl bg-background border border-surface-variant grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                      <div className="flex flex-col text-left gap-0.5">
                        <span className="text-[9px] text-outline font-semibold uppercase">Notas de la Reserva</span>
                        <p className="text-primary italic">"{booking.notes || 'Sin observaciones.'}"</p>
                      </div>

                      <div className="flex flex-col text-left gap-0.5 border-l border-surface-variant pl-4">
                        <span className="text-[9px] text-outline font-semibold uppercase">ID de Cliente</span>
                        <span className="text-primary font-semibold truncate max-w-[150px]">{booking.userId || 'Taquilla / POS'}</span>
                      </div>

                      <div className="flex flex-col text-right border-l border-surface-variant pl-4">
                        <span className="text-[9px] text-outline font-semibold uppercase">Importe Facturado</span>
                        <span className="font-black text-sm text-primary">
                          ${booking.totalAmount.toFixed(2)} {booking.currencyCode || 'USD'}
                        </span>
                      </div>
                    </div>

                    {/* Si está cancelado, mostrar motivo */}
                    {booking.statusName === 'Cancelled' && booking.notes && (
                      <div className="p-3 rounded-xl bg-error/5 border border-error/20 text-left text-error italic">
                        <strong>Motivo de Cancelación:</strong> "{booking.notes}"
                      </div>
                    )}

                    {/* Acciones administrativas */}
                    {(booking.statusName === 'Confirmed' || booking.statusName === 'Confirmada') && (
                      <div className="flex justify-end border-t border-surface-variant pt-4 mt-2">
                        <button 
                          onClick={() => handleCancel(booking)}
                          className="px-4 py-2 rounded-xl text-xs font-bold bg-error/10 hover:bg-error/20 text-error border border-error/20 transition-all cursor-pointer active:scale-95"
                        >
                          Cancelar y Liberar Cupos
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

    </div>
  );
};

export default AdminBookingListView;

// src/views/AdminBookingListView.vue
<script setup>
import { ref, computed } from 'vue'
import { useBookingStore } from '../stores/booking'
import Swal from 'sweetalert2'

const bookingStore = useBookingStore()

const searchQuery = ref('')
const selectedStatusFilter = ref('all') // all, confirmed, completed, cancelled
const expandedBookingId = ref('')

const toggleExpand = (id) => {
  if (expandedBookingId.value === id) {
    expandedBookingId.value = ''
  } else {
    expandedBookingId.value = id
  }
}

// Mapear statusIds
const getStatusName = (statusId) => {
  switch (statusId) {
    case 1: return 'Pending'
    case 2: return 'Confirmed'
    case 3: return 'Completed'
    case 4: return 'Cancelled'
    default: return 'Unknown'
  }
}

const getStatusClass = (statusId) => {
  switch (statusId) {
    case 1: return 'bg-yellow-500/10 text-yellow-500 border border-yellow-500/20'
    case 2: return 'bg-brand-emerald/10 text-brand-emerald border border-brand-emerald/20'
    case 3: return 'bg-brand-cyan/10 text-brand-cyan border border-brand-cyan/20'
    case 4: return 'bg-brand-rose/10 text-brand-rose border border-brand-rose/20'
    default: return 'bg-gray-800 text-gray-400'
  }
}

// Reservas filtradas por búsqueda y estado
const filteredBookings = computed(() => {
  return bookingStore.bookings.filter(b => {
    // Filtro por Estado
    if (selectedStatusFilter.value !== 'all') {
      const mapped = getStatusName(b.statusId).toLowerCase()
      if (mapped !== selectedStatusFilter.value) return false
    }

    // Filtro por Buscador (PNR, Nombre Pasajero, Atracción)
    if (searchQuery.value.trim()) {
      const q = searchQuery.value.toLowerCase()
      const matchPnr = b.pnrCode.toLowerCase().includes(q)
      const matchAttr = b.attractionName.toLowerCase().includes(q)
      const matchPassenger = b.passengers.some(
        p => `${p.firstName} ${p.lastName}`.toLowerCase().includes(q)
      )

      return matchPnr || matchAttr || matchPassenger
    }

    return true
  })
})

const handleCancel = (booking) => {
  Swal.fire({
    title: '¿Cancelar esta Reserva?',
    text: `Se liberarán los ${booking.passengers.length} cupos de vuelta al inventario. Escribe el motivo de la cancelación:`,
    input: 'text',
    inputPlaceholder: 'Ej: Taquilla cancela por fuerza mayor...',
    icon: 'warning',
    showCancelButton: true,
    background: '#111827',
    color: '#f3f4f6',
    confirmButtonColor: '#f43f5e',
    cancelButtonColor: '#374151',
    confirmButtonText: 'Sí, cancelar reserva',
    cancelButtonText: 'Cerrar',
    inputValidator: (value) => {
      if (!value) {
        return '¡Es obligatorio escribir un motivo!'
      }
    }
  }).then((result) => {
    if (result.isConfirmed) {
      const reason = result.value
      const success = bookingStore.cancelBooking(booking.id, reason)
      
      if (success.success) {
        Swal.fire({
          title: 'Reserva Cancelada',
          text: 'Los cupos se han liberado y el estado se actualizó a Cancelado.',
          icon: 'success',
          background: '#111827',
          color: '#f3f4f6',
          confirmButtonColor: '#10b981'
        })
      }
    }
  })
}
</script>

<template>
  <div class="flex flex-col gap-6 text-left">
    
    <!-- Encabezado -->
    <div class="flex flex-col gap-1 border-b border-white/5 pb-4">
      <router-link to="/admin" class="text-xs font-bold text-brand-cyan hover:underline flex items-center gap-1">
        ← Volver al Dashboard
      </router-link>
      <h1 class="text-2xl md:text-3xl font-extrabold text-white">Administrador de Reservas (PNR)</h1>
    </div>

    <!-- Buscador y Filtros Rápidos -->
    <div class="glass-panel rounded-2xl p-4 border border-white/10 flex flex-col md:flex-row gap-4 items-center justify-between shadow-lg">
      <!-- Buscador -->
      <div class="flex items-center rounded-xl bg-dark-900 border border-white/10 px-3 py-1.5 w-full md:max-w-sm">
        <span>🔍</span>
        <input 
          v-model="searchQuery"
          type="text" 
          placeholder="Buscar por PNR, pasajero o atracción..." 
          class="w-full bg-transparent border-none text-white text-xs pl-2 py-1 placeholder-gray-500 focus:outline-none"
        />
      </div>

      <!-- Filtro de Estados en Chips -->
      <div class="flex items-center gap-1.5 flex-wrap">
        <button 
          v-for="f in [
            { id: 'all', label: 'Todos' },
            { id: 'confirmed', label: 'Confirmadas' },
            { id: 'completed', label: 'Completadas' },
            { id: 'cancelled', label: 'Canceladas' }
          ]"
          :key="f.id"
          @click="selectedStatusFilter = f.id"
          class="px-3.5 py-1.5 rounded-lg text-[10px] font-bold uppercase transition-all cursor-pointer border"
          :class="selectedStatusFilter === f.id
            ? 'bg-brand-cyan/20 border-brand-cyan text-brand-cyan'
            : 'glass-card border-white/5 text-gray-400 hover:text-white'"
        >
          {{ f.label }}
        </button>
      </div>
    </div>

    <!-- Listado General de Reservas -->
    <div class="flex flex-col gap-4">
      
      <!-- Estado vacío -->
      <div v-if="filteredBookings.length === 0" class="glass-card rounded-2xl p-16 text-center border border-white/5 text-gray-500 text-xs">
        No se encontraron registros de reservas con el filtro de búsqueda seleccionado.
      </div>

      <div 
        v-else
        v-for="booking in filteredBookings" 
        :key="booking.id"
        class="glass-panel rounded-2xl border transition-all"
        :class="expandedBookingId === booking.id ? 'border-brand-cyan/30 shadow-lg shadow-brand-cyan/5' : 'border-white/5 hover:border-white/10'"
      >
        <!-- Tarjeta Contraída -->
        <div 
          @click="toggleExpand(booking.id)"
          class="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 cursor-pointer text-xs"
        >
          <!-- Info PNR y Atracción -->
          <div class="flex items-start gap-3">
            <span class="text-xl mt-0.5">🎫</span>
            <div class="flex flex-col text-left gap-0.5">
              <div class="flex items-center gap-2 flex-wrap">
                <span class="font-extrabold text-sm text-white font-mono uppercase tracking-wider text-brand-cyan">
                  {{ booking.pnrCode }}
                </span>
                <span class="font-bold text-gray-200 truncate w-40 md:w-56">{{ booking.attractionName }}</span>
              </div>
              <span class="text-[10px] text-gray-500 font-semibold">{{ booking.productTitle }}</span>
            </div>
          </div>

          <!-- Info Slot y Estado -->
          <div class="flex items-center justify-between md:justify-end gap-5 border-t border-white/5 md:border-none pt-3 md:pt-0">
            <div class="flex flex-col text-right pr-4 border-r border-white/10">
              <span class="text-[8px] text-gray-500 uppercase">Actividad programada</span>
              <span class="font-bold text-gray-200">{{ booking.slotDate }} | {{ booking.slotStartTime }} hs</span>
            </div>

            <div class="flex items-center gap-3">
              <span class="px-2.5 py-1 rounded-full text-[9px] font-bold uppercase tracking-wider" :class="getStatusClass(booking.statusId)">
                {{ booking.statusName }}
              </span>

              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="w-3.5 h-3.5 text-gray-500 transition-transform duration-200" :class="{ 'rotate-180': expandedBookingId === booking.id }">
                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
              </svg>
            </div>
          </div>
        </div>

        <!-- Seccion Detallada Desplegable -->
        <div v-if="expandedBookingId === booking.id" class="px-5 pb-5 border-t border-white/5 pt-4 flex flex-col gap-4 animate-fade-in text-xs">
          
          <!-- Roster de Pasajeros -->
          <div>
            <h4 class="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Detalle de Pasajeros Facturados</h4>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-2.5">
              <div 
                v-for="(p, pIdx) in booking.passengers" 
                :key="pIdx"
                class="p-3 rounded-xl bg-white/5 border border-white/5 flex flex-col gap-1 text-left"
              >
                <div class="font-bold text-gray-200">{{ p.fullName || `${p.firstName} ${p.lastName}` }}</div>
                <div class="flex justify-between text-[10px] text-gray-400 font-semibold">
                  <span>{{ p.documentType }}: {{ p.documentNumber }}</span>
                  <span class="text-brand-cyan">{{ p.priceTierLabel }} (${{ p.unitPrice.toFixed(2) }})</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Bitácora y Detalles del Cobro -->
          <div class="p-3.5 rounded-xl bg-white/5 border border-white/5 grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
            <!-- Notas/Origen -->
            <div class="flex flex-col text-left gap-0.5">
              <span class="text-[9px] text-gray-500 uppercase">Bitácora / Notas de la Reserva</span>
              <p class="text-gray-300 italic">"{{ booking.notes }}"</p>
            </div>

            <!-- Registro temporal -->
            <div class="flex flex-col text-left gap-0.5 border-l border-white/5 pl-4">
              <span class="text-[9px] text-gray-500 uppercase">Registrada en Sistema</span>
              <span class="text-gray-300 font-semibold">{{ new Date(booking.createdAt).toLocaleString('es-EC') }}</span>
            </div>

            <!-- Importe Total -->
            <div class="flex flex-col text-right border-l border-white/5 pl-4">
              <span class="text-[9px] text-gray-500 uppercase">Importe Total Recibido</span>
              <span class="font-black text-sm text-brand-emerald">${{ booking.totalAmount.toFixed(2) }} {{ booking.currencyCode }}</span>
            </div>
          </div>

          <!-- Si está cancelado, mostrar motivo -->
          <div v-if="booking.statusId === 4 && booking.cancelReason" class="p-3 rounded-xl bg-brand-rose/5 border border-brand-rose/25 text-left text-brand-rose">
            <strong>Motivo del Cierre:</strong> "{{ booking.cancelReason }}"
          </div>

          <!-- Acción Administrativa de Cierre/Cancelación -->
          <div class="flex justify-end border-t border-white/5 pt-4 mt-2" v-if="booking.statusId === 2">
            <button 
              @click="handleCancel(booking)"
              class="px-4 py-2 rounded-xl text-xs font-bold bg-brand-rose/10 hover:bg-brand-rose/20 text-brand-rose border border-brand-rose/20 hover:border-brand-rose/40 transition-all cursor-pointer"
            >
              Cancelar y Liberar Cupos
            </button>
          </div>

        </div>

      </div>
    </div>

  </div>
</template>
