// src/components/shared/Footer.tsx
import React from 'react';
import { Link } from 'react-router-dom';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-primary text-white pt-12 pb-8 border-t border-primary-container">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand Info */}
          <div className="space-y-4">
            <Link to="/" className="flex items-center space-x-2 text-xl font-bold tracking-tight text-white hover:opacity-95">
              <span className="material-symbols-outlined text-secondary-fixed-dim text-2xl">apartment</span>
              <span>HospédateEC</span>
            </Link>
            <p className="text-sm text-outline-variant leading-relaxed">
              Encuentra y reserva las mejores atracciones, tours y hospedajes en todo el Ecuador con confirmación instantánea y el respaldo de la plataforma líder del país.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-sm font-semibold text-tertiary-fixed-dim tracking-wider uppercase mb-4">
              Explorar
            </h3>
            <ul className="space-y-2 text-sm text-outline-variant">
              <li>
                <Link to="/explorar" className="hover:text-white transition-colors duration-200">
                  Catálogo de Atracciones
                </Link>
              </li>
              <li>
                <a href="#destinos" className="hover:text-white transition-colors duration-200">
                  Destinos Populares
                </a>
              </li>
              <li>
                <a href="#aventura" className="hover:text-white transition-colors duration-200">
                  Aventura & Naturaleza
                </a>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div>
            <h3 className="text-sm font-semibold text-tertiary-fixed-dim tracking-wider uppercase mb-4">
              Soporte
            </h3>
            <ul className="space-y-2 text-sm text-outline-variant">
              <li>
                <a href="#faq" className="hover:text-white transition-colors duration-200">
                  Preguntas Frecuentes
                </a>
              </li>
              <li>
                <a href="#terminos" className="hover:text-white transition-colors duration-200">
                  Términos de Servicio
                </a>
              </li>
              <li>
                <a href="#privacidad" className="hover:text-white transition-colors duration-200">
                  Políticas de Privacidad
                </a>
              </li>
            </ul>
          </div>

          {/* Contact */}
          <div>
            <h3 className="text-sm font-semibold text-tertiary-fixed-dim tracking-wider uppercase mb-4">
              Contacto
            </h3>
            <ul className="space-y-2 text-sm text-outline-variant">
              <li className="flex items-center space-x-2">
                <span className="material-symbols-outlined text-sm">mail</span>
                <span>soporte@hospedate.ec</span>
              </li>
              <li className="flex items-center space-x-2">
                <span className="material-symbols-outlined text-sm">phone</span>
                <span>+593 2-345-6789</span>
              </li>
              <li className="flex items-center space-x-2">
                <span className="material-symbols-outlined text-sm">location_on</span>
                <span>Quito, Pichincha, Ecuador</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-8 pt-8 border-t border-primary-container text-center text-xs text-outline-variant">
          <p>&copy; {new Date().getFullYear()} HospédateEC. Todos los derechos reservados. Desarrollado con los más altos estándares de calidad.</p>
        </div>
      </div>
    </footer>
  );
};

// src/components/Footer.vue
<template>
  <footer class="border-t border-white/5 bg-dark-900/90 py-8 mt-12">
    <div class="container mx-auto px-4 md:px-6 max-w-7xl">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        
        <!-- Info Principal -->
        <div class="md:col-span-2">
          <div class="flex items-center gap-2 mb-3">
            <span class="text-xl">✨</span>
            <span class="font-extrabold text-lg bg-gradient-to-r from-brand-cyan to-brand-violet bg-clip-text text-transparent">
              Atracciones Premium
            </span>
          </div>
          <p class="text-gray-400 text-sm max-w-sm leading-relaxed">
            Plataforma líder para la reserva de experiencias únicas, tours VIP y expediciones naturales con disponibilidad garantizada y control operativo de primer nivel.
          </p>
        </div>

        <!-- Enlaces Rápidos -->
        <div>
          <h4 class="text-sm font-bold text-gray-200 uppercase tracking-wider mb-3">Descubre</h4>
          <ul class="space-y-2 text-sm text-gray-400">
            <li><router-link to="/" class="hover:text-brand-cyan transition-colors">Inicio</router-link></li>
            <li><router-link to="/portal" class="hover:text-brand-cyan transition-colors">Mi Portal de Cliente</router-link></li>
            <li><a href="#" class="hover:text-brand-cyan transition-colors">Términos de Servicio</a></li>
            <li><a href="#" class="hover:text-brand-cyan transition-colors">Políticas de Privacidad</a></li>
          </ul>
        </div>

        <!-- Contacto e Integración -->
        <div>
          <h4 class="text-sm font-bold text-gray-200 uppercase tracking-wider mb-3">Integración</h4>
          <p class="text-gray-400 text-xs leading-relaxed mb-2">
            Proyecto de Integración de Microservicios. Arquitectura distribuida en .NET Core Web API y base de datos relacional Supabase.
          </p>
          <span class="inline-block px-2.5 py-1 rounded bg-white/5 text-[10px] text-gray-400 border border-white/5">
            OS: Windows Dev Env
          </span>
        </div>

      </div>

      <div class="border-t border-white/5 mt-8 pt-6 flex flex-col md:flex-row items-center justify-between gap-4">
        <span class="text-xs text-gray-500">
          &copy; 2026 Atracciones Premium. Todos los derechos reservados. Diseñado para wow.
        </span>
        <div class="flex items-center gap-4 text-xs text-gray-500">
          <span>Desarrollado con Vue 3 + Tailwind CSS</span>
          <span class="w-1.5 h-1.5 rounded-full bg-brand-emerald"></span>
          <span>Offline Simulator Mode</span>
        </div>
      </div>

    </div>
  </footer>
</template>
